#define UNICODE
#define _UNICODE
#include <windows.h>
#include <shellapi.h>
#include <swdevice.h>
#include <winhttp.h>
#include <iostream>
#include <string>
#include <vector>
#include <thread>
#include <chrono>
#include <regex>
#include <filesystem>
#include <stdexcept>
#pragma comment(lib,"user32.lib")
#pragma comment(lib,"gdi32.lib")
#pragma comment(lib,"shell32.lib")
#pragma comment(lib,"winhttp.lib")

struct FbInfo { int w=0,h=0,bpp=0; std::string format; size_t frame=0; };
static bool Crack(const std::wstring& u,std::wstring& host,INTERNET_PORT& port,std::wstring& prefix,bool& tls){ URL_COMPONENTS c{}; c.dwStructSize=sizeof(c); wchar_t h[256]{},p[4096]{}; c.lpszHostName=h;c.dwHostNameLength=_countof(h);c.lpszUrlPath=p;c.dwUrlPathLength=_countof(p); if(!WinHttpCrackUrl(u.c_str(),0,0,&c))return false; host.assign(h,c.dwHostNameLength);prefix.assign(p,c.dwUrlPathLength);while(!prefix.empty()&&prefix.back()==L'/')prefix.pop_back();port=c.nPort;tls=c.nScheme==INTERNET_SCHEME_HTTPS;return true; }
static std::string Get(const std::wstring& base,const std::wstring& path){ std::wstring host,prefix;INTERNET_PORT port;bool tls;if(!Crack(base,host,port,prefix,tls))throw std::runtime_error("bad URL"); HINTERNET s=WinHttpOpen(L"displayPost/0.1",WINHTTP_ACCESS_TYPE_AUTOMATIC_PROXY,nullptr,nullptr,0),c=nullptr,r=nullptr;if(!s)throw std::runtime_error("WinHttpOpen");c=WinHttpConnect(s,host.c_str(),port,0);if(!c)throw std::runtime_error("WinHttpConnect");r=WinHttpOpenRequest(c,L"GET",(prefix+path).c_str(),nullptr,WINHTTP_NO_REFERER,WINHTTP_DEFAULT_ACCEPT_TYPES,tls?WINHTTP_FLAG_SECURE:0);if(!r||!WinHttpSendRequest(r,WINHTTP_NO_ADDITIONAL_HEADERS,0,nullptr,0,0,0)||!WinHttpReceiveResponse(r,nullptr))throw std::runtime_error("HTTP GET failed");std::string out;char b[8192];DWORD n;while(WinHttpReadData(r,b,sizeof(b),&n)&&n)out.append(b,n);WinHttpCloseHandle(r);WinHttpCloseHandle(c);WinHttpCloseHandle(s);return out; }
static long Num(const std::string& j,const char*k){std::regex r(std::string("\\\"")+k+"\\\"\\s*:\\s*([0-9]+)");std::smatch m;if(!std::regex_search(j,m,r))throw std::runtime_error(std::string("fbinfo missing ")+k);return std::stol(m[1]);}
static FbInfo Fb(const std::wstring& u){std::string j=Get(u,L"/fbinfo");FbInfo f;f.w=Num(j,"width");f.h=Num(j,"height");f.bpp=Num(j,"bits_per_pixel");f.frame=(size_t)Num(j,"frame_size");if(j.find("\"format\":\"rgb565\"")==std::string::npos)throw std::runtime_error("only RGB565 is supported");return f;}
static bool Elevated(){HANDLE t=nullptr;if(!OpenProcessToken(GetCurrentProcess(),TOKEN_QUERY,&t))return false;TOKEN_ELEVATION e{};DWORD n;bool x=GetTokenInformation(t,TokenElevation,&e,sizeof(e),&n)&&e.TokenIsElevated;CloseHandle(t);return x;}
static int Elevate(){wchar_t exe[MAX_PATH];GetModuleFileNameW(nullptr,exe,MAX_PATH);int n;LPWSTR* a=CommandLineToArgvW(GetCommandLineW(),&n);std::wstring args;for(int i=1;i<n;i++){if(!args.empty())args+=L" ";args+=L"\""+std::wstring(a[i])+L"\"";}LocalFree(a);SHELLEXECUTEINFOW x{sizeof(x)};x.lpVerb=L"runas";x.lpFile=exe;x.lpParameters=args.c_str();x.nShow=SW_SHOW;if(!ShellExecuteExW(&x))return 1;WaitForSingleObject(x.hProcess,INFINITE);DWORD c=1;GetExitCodeProcess(x.hProcess,&c);CloseHandle(x.hProcess);return (int)c;}
static bool Install(const std::filesystem::path& inf){std::wstring p=L"/add-driver \""+inf.wstring()+L"\" /install";SHELLEXECUTEINFOW x{sizeof(x)};x.lpVerb=L"runas";x.lpFile=L"pnputil.exe";x.lpParameters=p.c_str();x.nShow=SW_HIDE;if(!ShellExecuteExW(&x))return false;WaitForSingleObject(x.hProcess,INFINITE);DWORD c=1;GetExitCodeProcess(x.hProcess,&c);CloseHandle(x.hProcess);return c==0;}
static HANDLE gDev=nullptr,gEvt=nullptr;static HRESULT gHr=E_FAIL;static void WINAPI Created(HSWDEVICE,HRESULT hr,PVOID p,PCWSTR){gHr=hr;SetEvent((HANDLE)p);}
static bool CreateDevice(){gEvt=CreateEventW(nullptr,TRUE,FALSE,nullptr);SW_DEVICE_CREATE_INFO i{};i.cbSize=sizeof(i);i.pszInstanceId=L"DisplayPost";i.pszzHardwareIds=L"DisplayPost\0\0";i.pszzCompatibleIds=L"DisplayPost\0\0";i.pszDeviceDescription=L"displayPost Virtual Display";i.CapabilityFlags=SWDeviceCapabilitiesRemovable|SWDeviceCapabilitiesSilentInstall|SWDeviceCapabilitiesDriverRequired;HRESULT h=SwDeviceCreate(L"DisplayPost",L"HTREE\\ROOT\\0",&i,0,nullptr,Created,gEvt,&gDev);return SUCCEEDED(h)&&WaitForSingleObject(gEvt,15000)==WAIT_OBJECT_0&&SUCCEEDED(gHr);}
struct Find{int w,h;RECT r{};bool ok=false;};static BOOL CALLBACK EnumMon(HMONITOR m,HDC,LPRECT,LPARAM lp){auto*f=(Find*)lp;MONITORINFO i{sizeof(i)};GetMonitorInfoW(m,&i);int w=i.rcMonitor.right-i.rcMonitor.left,h=i.rcMonitor.bottom-i.rcMonitor.top;if(!f->ok&&w==f->w&&h==f->h&&!(i.dwFlags&MONITORINFOF_PRIMARY)){f->r=i.rcMonitor;f->ok=true;}return TRUE;}
static bool FindMonitor(int w,int h,RECT&r){Find f{w,h};EnumDisplayMonitors(nullptr,nullptr,EnumMon,(LPARAM)&f);if(f.ok)r=f.r;return f.ok;}
class Capture{HDC s=nullptr,m=nullptr;HBITMAP b=nullptr;void*bits=nullptr;int w,h;public:std::vector<BYTE> out;bool Init(int W,int H){w=W;h=H;s=GetDC(nullptr);m=CreateCompatibleDC(s);BITMAPINFO i{};i.bmiHeader.biSize=sizeof(i.bmiHeader);i.bmiHeader.biWidth=w;i.bmiHeader.biHeight=-h;i.bmiHeader.biPlanes=1;i.bmiHeader.biBitCount=32;i.bmiHeader.biCompression=BI_RGB;b=CreateDIBSection(m,&i,DIB_RGB_COLORS,&bits,nullptr,0);if(!s||!m||!b)return false;SelectObject(m,b);out.resize((size_t)w*h*2);return true;}bool Frame(const RECT&r){if(!BitBlt(m,0,0,w,h,s,r.left,r.top,SRCCOPY|CAPTUREBLT))return false;auto*p=(uint32_t*)bits;auto*d=(uint16_t*)out.data();for(size_t i=0;i<(size_t)w*h;i++){uint32_t x=p[i];BYTE B=(BYTE)x,G=(BYTE)(x>>8),R=(BYTE)(x>>16);d[i]=(uint16_t)(((R>>3)<<11)|((G>>2)<<5)|(B>>3));}return true;}~Capture(){if(b)DeleteObject(b);if(m)DeleteDC(m);if(s)ReleaseDC(nullptr,s);}};
class Stream{HINTERNET s=nullptr,c=nullptr,r=nullptr;public:bool Open(const std::wstring&u){std::wstring h,p;INTERNET_PORT port;bool tls;if(!Crack(u,h,port,p,tls))return false;s=WinHttpOpen(L"displayPost/0.1",WINHTTP_ACCESS_TYPE_AUTOMATIC_PROXY,nullptr,nullptr,0);c=WinHttpConnect(s,h.c_str(),port,0);r=WinHttpOpenRequest(c,L"POST",(p+L"/fb").c_str(),nullptr,WINHTTP_NO_REFERER,WINHTTP_DEFAULT_ACCEPT_TYPES,tls?WINHTTP_FLAG_SECURE:0);LPCWSTR hd=L"Content-Type: application/octet-stream\r\n";return r&&WinHttpSendRequest(r,hd,(DWORD)-1,nullptr,0,WINHTTP_IGNORE_REQUEST_TOTAL_LENGTH,0);}bool Write(const void*p,DWORD n){return WinHttpWriteData(r,p,n,nullptr)!=FALSE;}~Stream(){if(r)WinHttpCloseHandle(r);if(c)WinHttpCloseHandle(c);if(s)WinHttpCloseHandle(s);}};
int wmain(){std::wcout<<L"displayPost URL: ";std::wstring url;std::getline(std::wcin,url);if(url.empty())return 1;try{FbInfo f=Fb(url);std::wcout<<L"fb0 "<<f.w<<L"x"<<f.h<<L" frame="<<f.frame<<L"\n";if(!Elevated())return Elevate();wchar_t e[MAX_PATH];GetModuleFileNameW(nullptr,e,MAX_PATH);auto inf=std::filesystem::path(e).parent_path()/L"driver"/L"IddSampleDriver.inf";if(!Install(inf))throw std::runtime_error("driver install failed");if(!CreateDevice())throw std::runtime_error("virtual display creation failed");RECT r{};for(int i=0;i<150&&!FindMonitor(f.w,f.h,r);i++)std::this_thread::sleep_for(std::chrono::milliseconds(100));if(!r.right&&!r.bottom)throw std::runtime_error("virtual monitor not found");Capture cap;if(!cap.Init(f.w,f.h))throw std::runtime_error("capture init failed");Stream st;if(!st.Open(url))throw std::runtime_error("open /fb failed");std::wcout<<L"Streaming...\n";while(cap.Frame(r)&&st.Write(cap.out.data(),(DWORD)cap.out.size()))std::this_thread::sleep_for(std::chrono::milliseconds(16));if(gDev)SwDeviceClose((HSWDEVICE)gDev);if(gEvt)CloseHandle(gEvt);return 0;}catch(const std::exception&e){std::cerr<<e.what()<<"\n";if(gDev)SwDeviceClose((HSWDEVICE)gDev);if(gEvt)CloseHandle(gEvt);return 1;}}
