#include <windows.h>
#include <winhttp.h>
#include <cstring>
#include <algorithm>
#include <chrono>
#include <cstdint>
#include <iostream>
#include <limits>
#include <regex>
#include <stdexcept>
#include <string>
#include <thread>
#include <vector>
#pragma comment(lib,"user32.lib")
#pragma comment(lib,"gdi32.lib")
#pragma comment(lib,"winhttp.lib")
struct Fb{int w=0,h=0,bpp=0,stride=0,ro=0,rl=0,go=0,gl=0,bo=0,bl=0,ao=0,al=0;size_t size=0;std::string fmt;};
struct Url{std::wstring host,path;INTERNET_PORT port;bool tls;};
static bool Crack(const std::wstring& s,Url&o){URL_COMPONENTS c{};c.dwStructSize=sizeof(c);wchar_t h[256]{},p[4096]{};c.lpszHostName=h;c.dwHostNameLength=_countof(h);c.lpszUrlPath=p;c.dwUrlPathLength=_countof(p);if(!WinHttpCrackUrl(s.c_str(),0,0,&c))return false;o.host.assign(h,c.dwHostNameLength);o.path.assign(p,c.dwUrlPathLength);if(o.path.empty())o.path=L"/";while(o.path.size()>1&&o.path.back()==L'/')o.path.pop_back();o.port=c.nPort;o.tls=c.nScheme==INTERNET_SCHEME_HTTPS;return true;}
static long N(const std::string&j,const char*k){std::regex r(std::string("\\\"")+k+"\\\"\\s*:\\s*([0-9]+)");std::smatch m;if(!std::regex_search(j,m,r))throw std::runtime_error(std::string("fbinfo missing ")+k);return std::stol(m[1]);}
static std::string S(const std::string&j,const char*k){std::regex r(std::string("\\\"")+k+"\\\"\\s*:\\s*\\\"([^\\\"]*)\\\"");std::smatch m;if(!std::regex_search(j,m,r))throw std::runtime_error(std::string("fbinfo missing ")+k);return m[1];}
static std::string Get(const std::wstring&base,const std::wstring&rel){Url u;if(!Crack(base,u))throw std::runtime_error("bad url");HINTERNET s=WinHttpOpen(L"displayPost/0.2",WINHTTP_ACCESS_TYPE_NO_PROXY,nullptr,nullptr,0),c=nullptr,r=nullptr;if(!s)throw std::runtime_error("WinHttpOpen");try{c=WinHttpConnect(s,u.host.c_str(),u.port,0);if(!c)throw std::runtime_error("connect");r=WinHttpOpenRequest(c,L"GET",(u.path+rel).c_str(),nullptr,WINHTTP_NO_REFERER,WINHTTP_DEFAULT_ACCEPT_TYPES,u.tls?WINHTTP_FLAG_SECURE:0);if(!r||!WinHttpSendRequest(r,nullptr,0,nullptr,0,0,0)||!WinHttpReceiveResponse(r,nullptr))throw std::runtime_error("GET failed");std::string out;char b[8192];for(;;){DWORD n=0;if(!WinHttpReadData(r,b,sizeof(b),&n))throw std::runtime_error("GET read failed");if(!n)break;out.append(b,b+n);}WinHttpCloseHandle(r);WinHttpCloseHandle(c);WinHttpCloseHandle(s);return out;}catch(...){if(r)WinHttpCloseHandle(r);if(c)WinHttpCloseHandle(c);WinHttpCloseHandle(s);throw;}}
static Fb Info(const std::wstring&u){auto j=Get(u,L"/fbinfo");Fb f;f.w=N(j,"width");f.h=N(j,"height");f.bpp=N(j,"bits_per_pixel");f.stride=N(j,"stride");f.size=(size_t)N(j,"frame_size");f.fmt=S(j,"format");f.ro=N(j,"red_offset");f.rl=N(j,"red_length");f.go=N(j,"green_offset");f.gl=N(j,"green_length");f.bo=N(j,"blue_offset");f.bl=N(j,"blue_length");f.ao=N(j,"alpha_offset");f.al=N(j,"alpha_length");if(f.w<=0||f.h<=0||f.stride<(f.w*f.bpp/8)||f.size<(size_t)f.stride*f.h||(f.bpp!=16&&f.bpp!=32))throw std::runtime_error("invalid fbinfo");return f;}
struct Mon{RECT r;bool primary;};
static BOOL CALLBACK EM(HMONITOR m,HDC,LPRECT,LPARAM p){MONITORINFO i{sizeof(i)};if(GetMonitorInfoW(m,&i))((std::vector<Mon>*)p)->push_back({i.rcMonitor,(i.dwFlags&MONITORINFOF_PRIMARY)!=0});return TRUE;}
static std::vector<Mon> Mons(){std::vector<Mon>v;EnumDisplayMonitors(nullptr,nullptr,EM,(LPARAM)&v);std::stable_sort(v.begin(),v.end(),[](auto&a,auto&b){return a.primary>b.primary;});return v;}
static int Sc(uint8_t x,int n){if(!n)return 0;if(n>=8)return x;return ((int)x*((1<<n)-1)+127)/255;}
static void Pack(BYTE*d,const Fb&f,BYTE b,BYTE g,BYTE r){uint32_t x=((uint32_t)Sc(r,f.rl)<<f.ro)|((uint32_t)Sc(g,f.gl)<<f.go)|((uint32_t)Sc(b,f.bl)<<f.bo);if(f.al)x|=((1u<<f.al)-1u)<<f.ao;for(int i=0;i<f.bpp/8;i++)d[i]=(BYTE)(x>>(i*8));}
class Capture{Fb f_;HDC screen_=nullptr,dc_=nullptr;HBITMAP bmp_=nullptr;void*bits_=nullptr;public:~Capture(){if(bmp_)DeleteObject(bmp_);if(dc_)DeleteDC(dc_);if(screen_)ReleaseDC(nullptr,screen_);}bool Init(const Fb&f){f_=f;screen_=GetDC(nullptr);dc_=screen_?CreateCompatibleDC(screen_):nullptr;if(!dc_)return false;BITMAPINFO b{};b.bmiHeader.biSize=sizeof(BITMAPINFOHEADER);b.bmiHeader.biWidth=f.w;b.bmiHeader.biHeight=-f.h;b.bmiHeader.biPlanes=1;b.bmiHeader.biBitCount=32;b.bmiHeader.biCompression=BI_RGB;bmp_=CreateDIBSection(dc_,&b,DIB_RGB_COLORS,&bits_,nullptr,0);if(!bmp_)return false;SelectObject(dc_,bmp_);SetStretchBltMode(dc_,COLORONCOLOR);return true;}bool Frame(const RECT&s,std::vector<BYTE>&out){int sw=s.right-s.left,sh=s.bottom-s.top;if(sw<=0||sh<=0)return false;double a=(double)sw/sh,t=(double)f_.w/f_.h;RECT d{0,0,f_.w,f_.h};if(a>t){d.bottom=(LONG)(f_.w/a+.5);d.top=(f_.h-d.bottom)/2;}else{d.right=(LONG)(f_.h*a+.5);d.left=(f_.w-d.right)/2;}RECT all{0,0,f_.w,f_.h};FillRect(dc_,&all,(HBRUSH)GetStockObject(BLACK_BRUSH));if(!StretchBlt(dc_,d.left,d.top,d.right-d.left,d.bottom-d.top,screen_,s.left,s.top,sw,sh,SRCCOPY))return false;const BYTE*src=(const BYTE*)bits_;out.assign(f_.size,0);int sb=f_.w*4,db=f_.bpp/8;if(f_.bpp==32&&f_.ro==16&&f_.rl==8&&f_.go==8&&f_.gl==8&&f_.bo==0&&f_.bl==8&&f_.al==0&&f_.stride==f_.w*4){for(int y=0;y<f_.h;y++)memcpy(out.data()+(size_t)y*f_.stride,src+(size_t)y*sb,(size_t)f_.w*4);return true;}for(int y=0;y<f_.h;y++){auto*sr=src+(size_t)y*sb;auto*dr=out.data()+(size_t)y*f_.stride;for(int x=0;x<f_.w;x++)Pack(dr+(size_t)x*db,f_,sr[x*4],sr[x*4+1],sr[x*4+2]);}return true;}};
class Stream{HINTERNET s_=nullptr,c_=nullptr,r_=nullptr;public:~Stream(){if(r_)WinHttpCloseHandle(r_);if(c_)WinHttpCloseHandle(c_);if(s_)WinHttpCloseHandle(s_);}bool Open(const std::wstring&base,size_t fs,uint64_t n){Url u;if(!Crack(base,u))return false;s_=WinHttpOpen(L"displayPost/0.2",WINHTTP_ACCESS_TYPE_NO_PROXY,nullptr,nullptr,0);c_=s_?WinHttpConnect(s_,u.host.c_str(),u.port,0):nullptr;r_=c_?WinHttpOpenRequest(c_,L"POST",(u.path+L"/fb").c_str(),nullptr,WINHTTP_NO_REFERER,WINHTTP_DEFAULT_ACCEPT_TYPES,u.tls?WINHTTP_FLAG_SECURE:0):nullptr;if(!r_)return false;LPCWSTR h=L"Content-Type: application/octet-stream\r\nExpect:\r\nCache-Control: no-cache\r\n";if(n&&fs<=UINT64_MAX/n&&fs*n<=std::numeric_limits<DWORD>::max())return WinHttpSendRequest(r_,h,(DWORD)-1,nullptr,0,(DWORD)(fs*n),0)!=FALSE;return WinHttpSendRequest(r_,h,(DWORD)-1,nullptr,0,WINHTTP_IGNORE_REQUEST_TOTAL_LENGTH,0)!=FALSE;}bool Write(const std::vector<BYTE>&f){return f.size()<=std::numeric_limits<DWORD>::max()&&WinHttpWriteData(r_,f.data(),(DWORD)f.size(),nullptr)!=FALSE;}};
static uint64_t Arg(const wchar_t*s){wchar_t*e=nullptr;auto x=_wcstoui64(s,&e,10);if(!s||!*s||!e||*e)throw std::runtime_error("invalid numeric argument");return x;}
int wmain(int argc,wchar_t**argv){if(argc<2){std::wcerr<<L"Usage: displayPost.exe <url> [frames=0] [monitor=1]\n";return 2;}try{std::wstring url=argv[1];uint64_t frames=argc>2?Arg(argv[2]):0,mi=argc>3?Arg(argv[3]):1;if(!mi)throw std::runtime_error("monitor must be >=1");Fb f=Info(url);auto ms=Mons();if(mi>ms.size())throw std::runtime_error("monitor out of range");Capture cap;if(!cap.Init(f))throw std::runtime_error("capture init failed");Stream st;if(!st.Open(url,f.size,frames))throw std::runtime_error("open /fb failed");std::vector<BYTE>frame;auto next=std::chrono::steady_clock::now();uint64_t sent=0;while(!frames||sent<frames){if(!cap.Frame(ms[(size_t)mi-1].r,frame)||!st.Write(frame))throw std::runtime_error("stream failed");++sent;next+=std::chrono::microseconds(33333);std::this_thread::sleep_until(next);}return 0;}catch(const std::exception&e){std::cerr<<"error: "<<e.what()<<"\n";return 1;}}
